language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # Use this little line of shell script to generate list of files to compile
    # for x in $(echo $(find WiserDevices -type f) | cat); echo "  - PLATFORMIO_CI_SRC="$x
    # --- General devices ---
        # Have been moved

    # Library Test
    - PLATFORMIO_CI_SRC=TATUDevice/examples/BasicTatuEthernet
    - PLATFORMIO_CI_SRC=TATUDevice/examples/BasicTatuWifi
    - PLATFORMIO_CI_SRC=TATUDevice/examples/attachmentsLibs

install:
    - pip install -U platformio
    # Install libraries needed
    - platformio lib install 17 19 61 89
    # Update libraries to prevent cache of old versions
    - platformio lib update 17 19 61 89

script:
    - platformio ci --lib="./TATUConfig" --lib="./TATUDevice" --lib="./TATUInterpreter" --lib="./sensors" --lib="./actuators" --board=uno --board=miniatmega328 --board=pro16MHzatmega328 --board=megaatmega2560 --board=megaatmega1280
